### PR TITLE
Add missing transfer encoding header for chunked

### PR DESCRIPTION
**Pull request by joelwurtz**
All in the title

### CODE REVIEW

**Comment by sagikazarmark** [comment]
:+1:

**Comment by dbu** [comment]
ups... :+1:
i guess this is just a bugfix, so we put that into 1.0 and tag 1.0.1 in a few days.

**Comment by sagikazarmark** [comment]
Agreed

**Comment by sagikazarmark** [comment]
@joelwurtz can you add this to the changelog?

**Comment by joelwurtz** [comment]
Added, do you mind if i release a 1.0.1 with this bug fixed (mainly to finally release docker-php in 1.0 ^^) ?

**Comment by sagikazarmark** [comment]
Go ahead 😊

Joel Wurtz notifications@github.com ezt írta (2016. január 29., péntek):

**Pull request merged**
