### PR TITLE
Updated doc block to be coherent with the suggested PSR

### LINKED ISSUE #51: Use new doc block for documenting array values
See [this resource](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#examples-12). Should we make doc blocks like this? 

``` php
    /**
     * @param UriInterface $baseUri
     * @param array        $config {
     *     @var bool $replace True will replace all hosts, false will only add host when none is specified.
     * }
     */
    public function __construct(UriInterface $baseUri, array $config = [])
    {
```

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix https://github.com/php-http/plugins/issues/51

### CODE REVIEW

**Comment by sagikazarmark** [comment]
LGTM. What about Style CI then?

**Comment by Nyholm** [comment]
StyleCI does not like this doc block. Should I comply with the patch that StyleCI provides? Or do you want to change the config in StyleCI?

**Comment by sagikazarmark** [comment]
Good question, have no idea. We could turn off some docblock check, maybe that helps.

**Comment by joelwurtz** [comment]
Certainly the align thing in docblock,

**Comment by joelwurtz** [comment]
I added this in php style ci config : 

```
disabled:
    - phpdoc_align
    - phpdoc_separation
```

Then it was ok, bug is coming from separation but if we only remove this, then align has another bug :/

**Comment by joelwurtz** [comment]
I think for the moment we should add the blank line proposed by the fixer, it's not a big problem, and we can try to do a PR on php-cs-fixer (at least an issue)

**Comment by sagikazarmark** [comment]
Ok, let's not add those disable statements then. I agree we can live with that extra line.

**Comment by dbu** [comment]
:+1:

**Comment by Nyholm** [comment]
Updated

**Pull request merged**
