### PR TITLE
improve isCacheable readability

### PR DESCRIPTION
**Pull request by dbu**
seems we have different ideas of code style. i think this is much more readable than what we did in #19

wdyt?

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Well, I don't mind after all.

**Comment by sagikazarmark** [comment]
@dbu do you have access to the repositories in StyleCI?

**Comment by dbu** [comment]
fixed the styling. seems that the github online editor is not that convenient for clean style...

**Comment by sagikazarmark** [comment]
:smile: 

At least it turned out that you do have access to StyleCI which is cool.

**Comment by Nyholm** [comment]
:+1:

**Pull request merged**
